version: '3.8'

services:
  postgres:
    container_name: blog-api
    image: postgres:15
    ports:
      - 5432:5432 # Troca a porta no host para 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: blog-api